### ISSUE TITLE
Simplify 'Clients' implementations  

### ISSUE THREAD

**Issue by xferra** [LtiLibrary/LtiLibrary#107]
Improve readability of `src/LtiLibrary.NetCore/Clients/` by reducing the amount of optional arguments:
https://github.com/andyfmiller/LtiLibrary/pull/104/files#diff-4b098b7e864ecf7e65911e929feea12aR33

imho 8+ args could be grouped in some kind of 'run context', or class converted to not-static and some args are passed to ctor, etc.

PS: Issue created as minor proposal during code review #104

**Comment by andyfmiller** [comment]
They are hard to read. [The team behind Identity Model had a somewhat analogous issue and switched to a new pattern using HttpClient extension methods](https://github.com/IdentityModel/IdentityModel2/releases/tag/3.8.0):

```
var message = new MessageParameters();
var client = _httpClientFactory.CreateClient();
await client.SendMessageAsync(message);
```

If we followed that pattern, it would probably make the code more readable. What do you think?

**Comment by andyfmiller** [comment]
Also, how much further should we take LtiLibrary for LTI 1.1? LTI 1.3 is coming fast and IMS is making a big push to convert. Will you go to 1.3?

**Comment by xferra** [comment]
It so happened that I do not touch LTI for months but I will be happy to improve this lib in my spare time 😉

**Comment by jeroenhabets** [comment]
Hi @xferra , long time no hear :) I believe you're no longer working in Ed-Tech. Since your PR never materialized AFAICT, and any effort would be better spent on sibling repo [LtiAdvantage](../../LtiAdvantage) as [IMS has deprecated LTI < 1.3](https://www.imsglobal.org/node/183196), I've now taken the liberty to close your ticket.

N.B. This LTILibrary here should basically be considered deprecated. It is still useful to support the few Tools/Platforms that have not migrated yet but [LTI Advantage](../../LtiAdvantage) (LTI 1.3) is the way forward.

**Comment by xferra** [comment]
Hi @jeroenhabets long time no see!

Yup, unfortunately, some ideas are destined not to come true 😔.

Agreed, this issue is no longer relevant.
