### ISSUE TITLE
Deep linking not complete according to IMS global

### ISSUE THREAD

**Issue by Abziz** [LtiLibrary/LtiLibrary#113]
According to [IMS global's specification for LTI deep linking](https://www.imsglobal.org/specs/lticiv1p0/specification-2) 
![image](https://user-images.githubusercontent.com/16762781/56269342-24fb8800-60fc-11e9-955c-b75c49162050.png)

There should be an option to create an [`AssignmentLinkItem`](http://www.imsglobal.org/lti/model/uml/purl.imsglobal.org/vocab/lti/v1/ci/index.html#AssignmentLinkItem) which has a single [`LineItem`](http://www.imsglobal.org/lti/model/uml/purl.imsglobal.org/vocab/lis/v2/outcomes/index.html#LineItem)

**Comment by Abziz** [comment]
suggestion:
create an `IAssignmentLinkItem ` interface and insert this after
```c#
  #region IAssignmentLinkItem Parameters 
  [JsonProperty("lineItem")]
  public LineItem LineItem { get; set; }
  #endregion 
```
after the following 

https://github.com/andyfmiller/LtiLibrary/blob/051ff1f66e3b5952a175673ef3d4b44aa64dee21/src/LtiLibrary.NetCore/Lti/v1/ContentItem.cs#L95-L105


you need to implement the interface as well.
(will submit a PR soon)

**Comment by jeroenhabets** [comment]
@Abziz Since your PR never materialized AFAICT, and any effort would be better spent on sibling repo [LtiAdvantage](../../LtiAdvantage) as [IMS has deprecated LTI < 1.3](https://www.imsglobal.org/node/183196) and embraced [Deeplinking](https://github.com/LtiLibrary/LtiAdvantage/tree/master/src/LtiAdvantage/DeepLinking) , I've now taken the liberty to close your ticket.

N.B. This LTILibrary here should basically be considered deprecated. It is still useful to support the few Tools/Platforms that have not migrated yet but [LTI Advantage](../../LtiAdvantage) (LTI 1.3) is the way forward.
