### ISSUE TITLE
Support for LTI v1.1.2

### ISSUE THREAD

**Issue by jmpease** [LtiLibrary/LtiLibrary#114]
Just curious to see if you were aware of the recent [LTI Security Update](https://www.imsglobal.org/spec/lti/security-update/v1p0) and had any plans or work in progress on supporting v1.1.2?

**Comment by srijken** [comment]
I think we should, and also we should be looking at v1.3 & Advantage

**Comment by amiller-ims** [comment]
I made a start on LTI Advantage [here](https://github.com/andyfmiller/LtiAdvantage). This was while it was in Candidate Final. Some things have changed since then. Let me know if you think it would be useful to move over here.

**Comment by jeroenhabets** [comment]
Since for LTI 1.3 / LTI Advantage this project has long moved on to sibling repo [LtiAdvantage](../../LtiAdvantage), I've now taken the liberty to close this ticket.

N.B. This LTILibrary here should basically be considered deprecated (as [IMS has deprecated LTI < 1.3](https://www.imsglobal.org/node/183196) in mentioned security bulletin). It is still useful to support the few Tools/Platforms that have not migrated yet but [LTI Advantage](../../LtiAdvantage) (LTI 1.3) is the way forward.
