### ISSUE TITLE
OAuth signature generation is sensitive to URL case.

### ISSUE THREAD

**Issue by The-Futurist** [LtiLibrary/LtiLibrary#23]
Andy,

We discovered what I think is a bug, in that the generated signature varies as the case of the URL varies. This caused us issues (in some special diagnostic support we've built for our LTI stuff).

I found this info that suggests it's a bug and that the URL should always be forced to lower case prior to generating a signature:

http://oauth.net/core/1.0/#sig_url

Thanks.

**Comment by jeroenhabets** [comment]
In case this issue is confirmed, could it please be fixed in a backward compatible way? (E.g. accept buggy and correct signatures)

Our company and our partners make extensive use of your library, so having to synchronize an upgrade is nigh impossible.

Thanks in advance,

**Comment by jeroenhabets** [comment]
@Korporal are you planning to submit a pull request?

**Comment by The-Futurist** [comment]
Hi, not unless this is agreed/confirmed. There are differing opinions on whether URLs should be treated in a case sensitive or insensitive manner, "fixing" the code could - conceivably - break stuff already out there so I'm not clear on whether we should or shouldn't make such a change.

**Comment by webatxcent** [comment]
I don't want to generalize, but I assume that since this is a .Net library the majority of the users/commenters are almost exclusively Microsoft/IIS. I have been watching this library for a little bit now with the intent on using it shortly, so I don't have any comment on the library. 

However I can offer this insight into the case sensitivity. We are also a 100% Microsoft shop, however **when dealing with Linux-based servers their URLs are case sensitive**. 

http://api.mysite.com/myresource 

is not the same as 

http://api.mysite.com/MyResource

and will result in a 404 or some other mapped response.

So the need to have the library treat URLs as case-sensitive is an artifact of how more than half of the webservers actually work. **I would urge NOT applying any case changing to supplied URLs.**

**Comment by andyfmiller** [comment]
@webatxcent @jeroenhabets - Since this would only affect the signature base string, I should only impact the signature. However, the signature is calculated on both sides (TC and TP), and there is a chance that the partners you have been working with are also incorrectly calculating the signature base string. So when LtiLibrary is fixed, interoperability with those partners will be broken.

**Comment by andyfmiller** [comment]
@Korporal - I think the [current code](https://github.com/andyfmiller/LtiLibrary/blob/master/LtiLibrary.Core/OAuth/OAuthUtility.cs#L25-L33), based on https://tools.ietf.org/html/rfc5849#section-3.4.1.2, is correct.

**Comment by andyfmiller** [comment]
@Korporal - I'm going to close this issue, but if you find out that most implementations of LTI are using http://oauth.net/core/1.0/#sig_url instead of https://tools.ietf.org/html/rfc5849#section-3.4.1.2, please let me know.
