### ISSUE TITLE
Invalid validation of LTI message

### ISSUE THREAD

**Issue by The-Futurist** [LtiLibrary/LtiLibrary#27]
I may be wrong but the code here seems to consider "user_id" a required LTI parameter. The spec however describes it as "recommended". Can you let me know your thoughts on this?

**Comment by jeroenhabets** [comment]
For our use-cases, both the Single Sign-On and Outcomes aspect of LTI are crucial to its success. We demand our partner providers to SSO using user_id and at the very least support Basic Outcomes (Outcomes 1.0) and partner consumers to uniquely identify users via user_id (and support Outcomes 1.0)

Outcomes (or SSO) without correct unique identifier of the learner does not make much sense.
Even in the old initial LTI v1.0 without Outcomes, the SSO aspect was providing the most value.

I was/am not aware that that this library considers user_id mandatory, but since LTI without user_id provides little value, I would consider it a feature if it does.

That said: @Korporal Do you have issues providing a user_id for your users?

**Comment by xferra** [comment]
@Korporal You're right, "user_id" is recommended and not mandatory according to spec. Would you like to prepare a pull request to fix it?

**Comment by xferra** [comment]
@Korporal I will close the issue as far as @andyfmiller already fixed it.
