### ISSUE TITLE
Throw an exception (when sending a request) if mandatory/required value was not provided.

### ISSUE THREAD

**Issue by andyfmiller** [LtiLibrary/LtiLibrary#38]
Throw an exception (when sending a request) if mandatory/required value was not provided.

**Comment by jeroenhabets** [comment]
One request: can we add some intelligence so e.g. if Outcomes 1.0 is used because lis_outcome_service_url is provided, then also lis_result_sourcedid becomes mandatory **[1]**.

When using Outcomes, the user_id should also be properly provided, in order for the provider to fill the mandatroy ResultAgent field (with LISPerson which in the end is a userId) **[2]**

Partner developers initially tend to forget and are not made aware of their omissions.

**[1]** See e.g. [6 Using Learning Information Services with LTI ](https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-6) at [https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-6](https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-6)
**[2]** See [http://www.imsglobal.org/lti/model/mediatype/application/vnd/ims/lis/v2p1/result%2Bjson/index.html#LISResult] and then [http://www.imsglobal.org/lti/model/mediatype/application/vnd/ims/lis/v2p1/result%2Bjson/index.html#LISPerson]

**Comment by andyfmiller** [comment]
I know at least one popular LMS will send lis_outcome_service_url even when there is no reasonable lis_result_sourcedid. Probably because the url is a fixed value and it is easier to send it every time. Regardless, I'm suspect it is intentional and they expect the tool publisher to use the missing sourcedId to mean the launch does not support Outcomes 1.0. At least that is how we treat a request like that at the company I work for.

In other words, I don't think either party thinks the missing sourcedId is an error, but as an intentional signal that Outcomes 1.0 is not supported for this launch. Perhaps we could add an optional helper method that inspects requests. For example, developers could choose to use it during dev/test.

Regarding the user_id in Outcomes 2.0, you are right (and I did not notice) that it **is** required to create a properly formed Outcomes 2.0 result, even though it is not technically required to successfully send the result to the right LineItem/Result combination and there is already enough information for the tool consumer to figure out where it goes (and presumably which user it was for). In other words, a missing value only affects the tool provider. But the tool provider can refuse to launch their tool in the first place if user_id is missing and return a reason to the lti_error url or directly to the user.

Since Outcomes 2.0 is still in public draft, I think this warrants a request to IMS to clarify the intention of making the user_id a required field (indirectly) of LISResult. I'll see if I can find the right forum.

**Comment by andyfmiller** [comment]
Please see pull request #40 for a method that can examine an LtiRequest for certain conditions. In this case Outcomes 1.0 parameters. And https://github.com/andyfmiller/LtiSamples/pull/9 for an example of how the tool consumer could inspect the request before sending.

**Comment by andyfmiller** [comment]
On the IMS forums I asked,

> Should LISPerson.userid be optional (0..1)?
> 
> Or have I misinterpreted LISPerson.userid? Does "A unique identifier for the person" mean it is or can be the TP's unique identifier for the person?

And Stephen Vickers replied,

> Yes it is intentional.  Without an ID there is no way of identifying the user to which the LISPerson object belongs, or whose result object is being accessed.  It must also be the Tool Consumer's ID for the user otherwise they will not know which user's result is being referenced.

This is an interesting situation...a recommended (but not required) launch parameter is required if the TC wants to receive Outcomes 2 results.

**Comment by andyfmiller** [comment]
@jeroenhabets Please check out the changes in pull request 40. CheckForRequiredLtiParameters has been moved to the LtiRequest class so it can be called by either/both the tool consumer and tool provider. And it has been enhanced to check for required Outcomes 1.0 and Outcomes 2.0 parameters.

**Comment by srijken** [comment]
@xferra I would indeed say so. Closing because of #40
