### ISSUE TITLE
In Outcomes 2.0 @context is mandatory (at least one) and has a default for each type.

### ISSUE THREAD

**Issue by jeroenhabets** [LtiLibrary/LtiLibrary#39]
We found out via the LISResult because [http://ltiapps.net/test/tc.php](http://ltiapps.net/test/tc.php) did not accept our Outcomes, so I'll give LISResult as an example here:

LISResult is a LD-JSON object (like the other Outcomes 2.0 objects) specified here:
http://www.imsglobal.org/lti/model/mediatype/application/vnd/ims/lis/v2p1/result%2Bjson/index.html#LISResult

> @context Type: JSON-LD Context
> Mult: 1..* 
> Description: This value specifies one or more JSON-LD contexts, either by reference or by value. When multiple contexts are specified, they must be encapsulated within an array.
>For most implementations, the value will be the single URI for the standard context associated with the application/vnd.ims.lis.v2p1.result+json media type. In this case, the value will be
>    **"http://purl.imsglobal.org/ctx/lis/v2p1/Result"**

NOTE: At least one value for "@context" needs to be provided. A constant for the default contexts is already defined in [LtiConstants.cs](https://github.com/andyfmiller/LtiLibrary/blob/master/LtiLibrary.Core/Common/LtiConstants.cs). For LisResult it is "ResultContextId"

NOTE: Multiple values for "@context" should be supported according to the spec (`"@context" : [ ... ],`)

**Comment by jeroenhabets** [comment]
I have logged this issue as https://github.com/andyfmiller/LtiLibrary/issues/34 is now closed in probably a unsatisfactory way: There is a default in the spec so the library should add it if not done explicity by the developer.
NOTE: The other Outcomes 2.0 objects have the same requirement and therefore the same issue.

**Comment by andyfmiller** [comment]
When I initially wrote the Outcomes 2.0 objects, I included a default context for every object. But I removed them on June 8, 2015 with the rather cryptic comment "Simplified constructor".

https://github.com/andyfmiller/LtiLibrary/commit/43007069ee2e7736338602ea648a6d7c05254347

I do not recall what the real reason was, but I'm pretty sure I was having a lot of trouble serializing/deserializing JSON-LD objects with default constructors and the complicated rules for @context.

Correctly serializing/deserializing a JSON-LD object is hard...complicated by the unusual rules for creating @context and the prefixes that can be defined on the fly. Try using http://json-ld.org/ to parse the various json-ld samples in the Outcomes 2.0 documentation. Even that site has trouble.

In the IMS forums there is some pushback regarding JSON-LD...especially around Outcomes 2.0. We may not be using JSON-LD correctly, it is hard to serialize in any language, and there may not be much value compared to simply agreeing on a format (no need for a context). There are no real-life examples of anyone "discovering" the format of a LineItem for example.

I know I can't and don't want to write another "real" json-ld serializer/deserializer for Outcomes 2.0. I found https://github.com/NuGet/json-ld.net back in 2015, but it had been inactive for a year and I could not get it working. I see that it has since become active again and probably worth looking at. There is also a new project worth looking at https://github.com/wikibus/JsonLD.Entities. I'll poke around with those two github projects to see if one or the other will work. If so, then perhaps I can tackle this issue again.

Do you have another approach?

**Comment by jeroenhabets** [comment]
I was blissfully unaware of these complexities.

Is it an idea, to just do the minimal: if no context is provided by the developer (as user of the library), sent the default from the spec? At least this way, ltiapps would accept the LISResult (Outcomes 2.0)...

**Comment by andyfmiller** [comment]
I asked a question about the Outcomes 2.0 spec last week on the IMS forum. The answer was the service I was asking about was being redesigned. I don't think the current draft will be released. I would prefer to wait on making any enhancements until either the current draft is accepted or a new draft is proposed.

**Comment by andyfmiller** [comment]
Merged basic LTI checks for required fields into code base.

**Comment by jeroenhabets** [comment]
@andyfmiller I'll close my own ticket as well. We have moved to LTI 1.3 and are using sibling repo [LtiAdvantage](../../LtiAdvantage).

As [IMS has deprecated LTI < 1.3](https://www.imsglobal.org/node/183196) we have ended our support for LTI 1.1 also in the interest of our users and customers (who are rather compliance/security aware).
