### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by sccarson** [LtiLibrary/LtiLibrary#54]
I am trying to implement Outcomes v2 in my application. The consumer I am testing against is moodle. I have done the folllowing:

LtiLibrary.Core.Outcomes.v2.LisResult result = new LtiLibrary.Core.Outcomes.v2.LisResult();
LtiLibrary.Core.Outcomes.v2.LisPerson person = new LtiLibrary.Core.Outcomes.v2.LisPerson();

result.Comment = “Good Job”;
result.ResultAgent = person;

result.ResultScore = “50%”;
result.TotalScore = 5;

Exception ex = LtiLibrary.Core.Outcomes.v2.OutcomesClient.PostResult(result, Request.Form[“lis_outcome_service_url”].ToString(), Request.Form[“oauth_consumer_key”].ToString(), clsLtiParams.SharedSecret).Exception;

My question is where does the parameters defined in lis_result_sourcedid go. I understand that currently there is no reference to a user in the LMS. How do i do this?

**Comment by andyfmiller** [comment]
Outcomes 2 is still is draft form, so it is very likely to change. But as it stands now, you post the result to the ResultServiceUrl (not the lis_outcome_service_url). And the ResultServiceUrl will have have the equivalent of the lis_result_sourcedid embedded somewhere in the URL. As a tool provider, you don't need to keep track of it. The flow goes something like this:

1. When you configure your external tool in Moodle, add a custom parameter for Moodle to pass the ResultServiceUrl to you. For example, custom_result_service_url=$Results.url. If Moodle supports Outcomes 2.0, it will replace $Results.url with the ResultsServiceUrl that is specific to this particular launch.
2. When you are ready to send a result to Moodle, use PostResult(result, Request.Form["custom_result_service_url"].ToString(), ....);
3. Because Moodle generated a specific ResultsServiceUrl for the launch, it will know where to save the result.

**Comment by andyfmiller** [comment]
I checked in with IMS and they will release the new Assignment and Grade Services 2.0 spec early next year (2018). I have not seen the draft, but the person I communicated with thought it was very different than Outcomes 2.0.

https://www.imsglobal.org/activity/learning-tools-interoperability

I'm going to close this issue now. We we can continue the discussion next year if needed.
