### ISSUE TITLE
.net Framework 4.0

### ISSUE THREAD

**Issue by lylia** [LtiLibrary/LtiLibrary#9]
there is no compatibility with .Net Framework 4.0 ?

**Comment by jeroenhabets** [comment]
As a user and not the library author this is _**not** an authorative answer_ but: 

No, the library is not compatible with .Net 4.0. (Last year we have upgraded our platform to 4.5 in order to be able to utilize this LTI library). One of the drivers behind it is that Microsoft ASP.NET Web API 2 depends on .Net 4.5

**Comment by lylia** [comment]
thanks for the confirmation

**Comment by lylia** [comment]
LTI Library is not compatible with .Net Framework 4.0 but 4.5 and later
