### ISSUE TITLE
Request for Release Notes

### ISSUE THREAD

**Issue by CreepyGnome** [LtiLibrary/LtiLibrary#96]
I was looking for some form of release note as to what changed between your LTI Library 2.x and 3.x since it was a major version release.  I checked the readme, wiki, and your blog.  If I missed it could you provide a like to it. If not I would love to know what changed between the 2.x and 3.x releases. Especially if there are breaking changes. We are currently using 2.2.0 and before we upgrade to 3.1.1 we really would like to know what we are getting into and if there are anything new we would like to use or issues we will need to address and change due to breaking changes.

**Comment by andyfmiller** [comment]
There are some release notes in [Releases](https://github.com/andyfmiller/LtiLibrary/releases). But I agree it is hard to know if there are breaking changes, or what they are.

Here is a comparison between the [2.2.0 release and 3.1.1](https://github.com/andyfmiller/LtiLibrary/compare/b011d8f...c1ead8f). IIRC, these are the breaking changes:

* [Update to NET Core 2.0](https://github.com/andyfmiller/LtiLibrary/commit/cfcac1e546feae53624f116ef6e004076c0dfb92)
* [Change targets to netstandard1.6 and netstandard2.0](https://github.com/andyfmiller/LtiLibrary/commit/6e0c69351f87333082ed966a068d032695b64be5)
* [Add support for Institutional and System Roles](https://github.com/andyfmiller/LtiLibrary/commit/5fcd4def09cfcc2761e1073665ac50944f7a53e6) - breaking because Role was renamed ContextRole.
